CREATE TABLE IF NOT EXISTS accommodation_applications (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    certification_track TEXT NOT NULL DEFAULT 'locally_certified',
    application_type TEXT NOT NULL,
    application_date TEXT,
    establishment_name TEXT NOT NULL,
    owner_name TEXT NOT NULL,
    address TEXT NOT NULL,
    telephone TEXT,
    mobile_number TEXT,
    email TEXT,
    facebook TEXT,
    category TEXT NOT NULL,
    total_rooms INTEGER,
    total_capacity INTEGER,
    total_employees INTEGER,
    male_employees INTEGER,
    female_employees INTEGER,
    year_started TEXT,
    room_types TEXT,
    amenities TEXT,
    previous_certificate TEXT,
    renewal_date TEXT,
    applicant_signature TEXT NOT NULL,
    status TEXT DEFAULT 'pending',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
